blank_issues_enabled: false
contact_links:
  - name: OpenFABR Community Discord
    url: https://discord.gg/jsKcF6p9
    about: Please ask and answer questions here.
  - name: OpenFABR Security Report
    url: https://security.open.fabrhq.com
    about: Please report security vulnerabilities here.